SELECT * FROM TAB;
SELECT * FROM ORDERS;
DROP TABLE CATEGORIES;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID VARCHAR2(15) PRIMARY KEY, 
CUSTOMERS_NAME VARCHAR2(15) NOT NULL,
ADDRESS VARCHAR2(15) NULL,
CITY VARCHAR2(15) NULL,
POSTAL_CODE VARCHAR2(15) NULL
);
CREATE TABLE EMPLOYEES(
EMPLOYEES_ID VARCHAR2(15) PRIMARY KEY,
LAST_NAME VARCHAR2(15) NOT NULL,
FIRST_NAME VARCHAR2(15) NOT NULL,
BIRTH_DATE VARCHAR2(15) NOT NULL,
PHOTO VARCHAR2(15) DEFAULT '파일명',
NOTES VARCHAR2(15) DEFAULT '메모'
);
CREATE TABLE SHIPPERS(
SHIPPER_ID VARCHAR2(15)  PRIMARY KEY,
SHIPPER_NAME VARCHAR2(15) NOT NULL,
PHONE VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE ORDER_ID
START WITH 1
INCREMENT BY 1;

CREATE TABLE ORDERS(
ORDER_ID NUMBER PRIMARY KEY,
CUSTOMER_ID VARCHAR2(15),
CONSTRAINT ORDERS_FK_CUSTOMERS FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID),
    
EMPLOYEES_ID VARCHAR2(15),
CONSTRAINT ORDERS_FK_EMPLOYEES FOREIGN KEY(EMPLOYEES_ID)
    REFERENCES EMPLOYEES(EMPLOYEES_ID),
    
ORDERDATE DATE DEFAULT SYSDATE,

SHIPPER_ID VARCHAR2(15),
CONSTRAINT ORDERS_FK_SHIPPERS FOREIGN KEY(SHIPPER_ID)
    REFERENCES SHIPPERS(SHIPPER_ID)
);

CREATE TABLE SUPPLIERS(
SUPPLIER_ID VARCHAR2(15) PRIMARY KEY,
SUPPLIER_NAME VARCHAR2(15) NOT NULL,
ADDRESS VARCHAR2(15) NOT NULL,
CITY VARCHAR2(15) NOT NULL,
POSTALCODE VARCHAR2(15) NOT NULL,
PHONE VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE CATEGORY_ID
START WITH 1000
INCREMENT BY 1;

CREATE TABLE CATEGORIES(
CATEGORY_ID NUMBER PRIMARY KEY,
CATEGORY_NAME VARCHAR2(15) NOT NULL,
DESCRIPTION VARCHAR2(15)
);

CREATE SEQUENCE PRODUCTS_ID
START WITH 2000
INCREMENT BY 1; 
SELECT * FROM TAB;

CREATE TABLE PRODUCTS(
PRODUCTS_ID NUMBER PRIMARY KEY,
PRODUCT_NAME VARCHAR2(15) NOT NULL,
SUPPLIER_ID VARCHAR2(15),
CONSTRAINT PRODUCTS_FK_SUPPLIERS FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIERS(SUPPLIER_ID),
CATEGORY_ID NUMBER,
CONSTRAINT PRODUCTS_FK_CATEGORIES FOREIGN KEY(CATEGORY_ID)
    REFERENCES CATEGORIES(CATEGORY_ID),
UNIT VARCHAR2(15) NOT NULL,
PRICE NUMBER DEFAULT 0
);


CREATE SEQUENCE ORDERDETAIL_ID
START WITH 3000
INCREMENT BY 1;

CREATE TABLE ORDER_DETAILS(
ORDERDETAIL_ID NUMBER PRIMARY KEY,
ORDER_ID NUMBER,
CONSTRAINT ORDERDETAILS_FK_ORDERS FOREIGN KEY(ORDER_ID)
    REFERENCES ORDERS(ORDER_ID),
PRODUCTS_ID NUMBER,
CONSTRAINT ORDERDETAILS_FK_PRODUCTS FOREIGN KEY(PRODUCTS_ID)
    REFERENCES PRODUCTS(PRODUCTS_ID),
QUANTITY NUMBER DEFAULT 0
);



SELECT * FROM TAB;

DROP TABLE PRODUCTS;