SELECT * FROM CUSTOMERS;



--1. 현재 목록에서 ROWNUM을 추가한다

SELECT ROWNUM "NO.",C.*
FROM CUSTOMERS C; 

--2. ROWNUM을 역순으로 정렬한다.

SELECT ROWNUM RNUM ,C.*
FROM CUSTOMERS C
ORDER BY RNUM DESC; 

--3. 페이지사이즈(5)만큼만 출력한다

SELECT T.*
FROM (SELECT ROWNUM RNUM ,C.* 
        FROM CUSTOMERS C 
        ORDER BY ROWNUM DESC) T
WHERE T.RNUM BETWEEN 1 AND 31;

SELECT COUNT(*) AS COUNT FROM CUSTOMERS;

DELETE FROM CUSTOMERS
     WHERE PASSWORD = 123456 ;


SELECT T2.*
FROM (SELECT ROWNUM R2,T.* 
        FROM (SELECT ROWNUM RNUM, T.* 
        FROM CUSTOMERS C 
        ORDER BY RNUM DESC) T) T2
WHERE R2 BETWEEN 1 AND 5;

SELECT T2.*
FROM(SELECT ROWNUM R2,T.*
FROM (SELECT ROWNUM RNUM ,C.*
FROM CUSTOMERS C  
ORDER BY RNUM DESC) T) T2
WHERE R2 BETWEEN 1 AND 30 ;

SELECT CUSTOMER_ID,CUSTOMER_NAME,PHONE
FROM CUSTOMERS;




UPDATE CUSTOMERS
SET phone = '010-66310240',city = '도마동 63-6',address='35333',postal_Code ='대전광역시 서구 용화6길 20' ,password ='0000' 
WHERE CUSTOMER_ID = 'gusdn1231';


Commit;
