SELECT * FROM CUSTOMERS;



--1. 현재 목록에서 ROWNUM을 추가한다

SELECT ROWNUM "NO.",C.*
FROM CUSTOMERS C; 

--2. ROWNUM을 역순으로 정렬한다.

SELECT ROWNUM RNUM ,C.*
FROM CUSTOMERS C
ORDER BY RNUM DESC; 

--3. 페이지사이즈(5)만큼만 출력한다

SELECT T.*
FROM (SELECT ROWNUM RNUM ,C.* 
        FROM CUSTOMERS C 
        ORDER BY ROWNUM DESC) T
WHERE T.RNUM BETWEEN 1 AND 31;

SELECT COUNT(*) AS COUNT FROM CUSTOMERS;

DELETE FROM CUSTOMERS
     WHERE PASSWORD = 123456 ;

