SELECT * FROM CUSTOMERS;
SELECT * FROM IMAGE;

TRUNCATE TABLE IMAGE;

INSERT INTO IMAGE VALUES(IMG_SEQ.NEXTVAL, 'default_image','png','default');


DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAILS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE SHIPPERS CASCADE CONSTRAINTS;
DROP TABLE SUPPLIERS CASCADE CONSTRAINTS;
DROP SEQUENCE ORDER_ID;
DROP SEQUENCE CATEGORY_ID;
DROP SEQUENCE PRODUCTS_ID;
DROP SEQUENCE ORDERDETAIL_ID;