
SELECT IMG_SEQ 
FROM IMAGE 
WHERE IMG_SEQ LIKE ((SELECT MAX(IMG_SEQ) 
                            FROM IMAGE));
                          
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;

SELECT *FROM SUPPLIERS;
SELECT *FROM PRODUCTS;
 

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S3','삼성','DEFAULT','PHONE','300000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S4','삼성','DEFAULT','PHONE','400000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S5','삼성','DEFAULT','PHONE','500000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S6','삼성','DEFAULT','PHONE','600000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S7','삼성','DEFAULT','PHONE','700000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S8','삼성','DEFAULT','PHONE','800000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S9','삼성','DEFAULT','PHONE','900000');

INSERT INTO PRODUCTS(PRODUCTS_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES(PRODUCTS_ID.NEXTVAL,'Galaxy S10','삼성','DEFAULT','PHONE','1000000');


SELECT * FROM tab;

CREATE TABLE SUPPLIERS(
SUPPLIER_ID VARCHAR2(15) PRIMARY KEY,
SUPPLIER_NAME VARCHAR2(15) NOT NULL,
ADDRESS VARCHAR2(15) NOT NULL,
CITY VARCHAR2(15) NOT NULL,
POSTALCODE VARCHAR2(15) NOT NULL,
PHONE VARCHAR2(15) NOT NULL
);

CREATE TABLE PRODUCTS(
PRODUCTS_ID NUMBER PRIMARY KEY,
PRODUCT_NAME VARCHAR2(15) NOT NULL,
SUPPLIER_ID VARCHAR2(15),
CONSTRAINT PRODUCTS_FK_SUPPLIERS FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIERS(SUPPLIER_ID),
CATEGORY_ID NUMBER,
CONSTRAINT PRODUCTS_FK_CATEGORIES FOREIGN KEY(CATEGORY_ID)
    REFERENCES CATEGORIES(CATEGORY_ID),
UNIT VARCHAR2(15) NOT NULL,
PRICE NUMBER DEFAULT 0
);

UPDATE CUSTOMERS SET PHONE = 01099473080 WHERE PHONE LIKE '010-9947-3080';

ALTER TABLE CUSTOMERS RENAME COLUMN POSTALCODE TO POSTAL_CODE;

DROP TABLE IMAGE;
SELECT * FROM USER_SEQUENCES;

create sequence IMG_SEQ 
start with 1 
increment BY 1 
maxvalue 10000;
SELECT *FROM CATEGORIES;
CREATE TABLE IMAGE(
    IMG_SEQ NUMBER PRIMARY KEY,
    IMG_NAME VARCHAR2(50),
    IMG_EXTENTION VARCHAR2(50),
    OWNER VARCHAR2(50)
);

INSERT INTO CATEGORIES(CATEGORY_ID,CATEGORY_NAME,DESCRIPTION)
VALUES(CATEGORY_ID.NEXTVAL,'NOTEBOOK','DESCRIPTION');

SELECT IMG_SEQ.NEXTVAL FROM DUAL;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID VARCHAR2(15) PRIMARY KEY, 
CUSTOMER_NAME VARCHAR2(15) NOT NULL,
PASSWORD VARCHAR2(15) NOT NULL,
SSN VARCHAR2(15) NOT NULL,
PHONE VARCHAR2(15) NOT NULL,
POSTAL_CODE VARCHAR2(60) NOT NULL,
CITY VARCHAR2(60) NOT NULL,
ADDRESS VARCHAR2(60) NOT NULL,
PHOTO VARCHAR2(60) DEFAULT 'default_photo'
);
select * from customers;
--1. 현재 목록에서 ROWNUM을 추가한다

SELECT ROWNUM "NO.",C.*
FROM CUSTOMERS C; 

--2. ROWNUM을 역순으로 정렬한다.

SELECT ROWNUM RNUM ,C.*
FROM CUSTOMERS C
ORDER BY RNUM DESC; 

--3. 페이지사이즈(5)만큼만 출력한다

SELECT T.*
FROM (SELECT ROWNUM RNUM ,C.* 
        FROM CUSTOMERS C 
        ORDER BY ROWNUM DESC) T
WHERE T.RNUM BETWEEN 1 AND 31;

SELECT COUNT(*) AS COUNT FROM CUSTOMERS;

DELETE FROM PRODUCTS
     WHERE PRODUCT_NAME = 'Galaxy S2' ;


SELECT T2.*
FROM (SELECT ROWNUM R2,T.* 
        FROM (SELECT ROWNUM RNUM, T.* 
        FROM CUSTOMERS C 
        ORDER BY RNUM DESC) T) T2
WHERE R2 BETWEEN 1 AND 5;

SELECT T2.*
FROM(SELECT ROWNUM R2,T.*
FROM (SELECT ROWNUM RNUM ,C.*
FROM CUSTOMERS C  
ORDER BY RNUM DESC) T) T2
WHERE R2 BETWEEN 1 AND 30 ;

SELECT CUSTOMER_ID,CUSTOMER_NAME,PHONE
FROM CUSTOMERS;

DELETE 
FROM PRODUCTS
WHERE SUPPLIER_ID LIKE '1040';

UPDATE PRODUCTS
SET PRODUCT_NAME = 'Galaxy NOTE 7'
WHERE PRODUCTS_ID = '2053';


Commit;
