-- EMPLOYEES테이블
--[ employee_id = 번호 ] [ first_name = 이름 ] 
--[ last_name = 성 ] [ email = 이메일 ] 
--[ phone_number = 전화번호 ] [ hire_date = 고용일 ]
--[ job_id = 업무ID ] [ salary = 급여]
--[ commission_pct = 커미션비율 ] [ manager_id = 상사ID]
--[ department_id = 부서ID]

DESC EMPLOYEES;
CREATE VIEW EMP AS
SELECT
   EMPLOYEE_ID EID,
   FIRST_NAME FNAME,
   LAST_NAME LNAME,
   EMAIL,
   HIRE_DATE HDATE,
   JOB_ID JID,
   SALARY SAL,
   COMMISSION_PCT COMM,
   MANAGER_ID MID,
   DEPARTMENT_ID DID
FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;

DESC JOBS;
CREATE VIEW JOB AS
SELECT
   JOB_ID JID,
   JOB_TITLE TITLE,
   MIN_SALARY MINSAL,
   MAX_SALARY MAXSAL
FROM JOBS;
SELECT * FROM JOBS;

DESC DEPARTMENTS;
CREATE VIEW DEP AS
SELECT
DEPARTMENT_ID DID,
DEPARTMENT_NAME DNAME,
MANAGER_ID MID,
LOCATION_ID LID
FROM DEPARTMENTS;

DESC LOCATIONS;
CREATE VIEW LOC AS
SELECT
LOCATION_ID LID,
STREET_ADDRESS ADDR,
POSTAL_CODE ZIP,
CITY,
STATE_PROVINCE PROV,
COUNTRY_ID CID
FROM LOCATIONS;

SELECT * FROM LOCATIONS;

DESC JOB_HISTORY;
CREATE VIEW HIS AS
SELECT
    EMPLOYEE_ID EID,
    START_DATE SDATE,
    END_DATE EDATE,
    JOB_ID JID,
    DEPARTMENT_ID DID
    FROM JOB_HISTORY;
