--1단계
SELECT P.BIRTH_DATE 생년월일, P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC;



--2단계
SELECT P.BIRTH_DATE 생년월일, P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
AND ROWNUM BETWEEN 1 AND 5
ORDER BY P.BIRTH_DATE DESC;



--3단계
SELECT BIRTH_DATE 생년월일, PLAYER_NAME 선수
FROM (SELECT BIRTH_DATE,PLAYER_NAME
        FROM PLAYER 
        WHERE BIRTH_DATE IS NOT NULL
        ORDER BY BIRTH_DATE DESC )
WHERE ROWNUM BETWEEN 1 AND 5;


--4단계
SELECT BIRTH_DATE 생년월일, PLAYER_NAME 선수
FROM (SELECT BIRTH_DATE,PLAYER_NAME
        FROM PLAYER 
        WHERE BIRTH_DATE IS NOT NULL
        ORDER BY BIRTH_DATE DESC )
WHERE ROWNUM BETWEEN 6 AND 10;


SELECT RNUM AS "NUMBER" ,BIRTH_DATE 생년월일 ,PLAYER_NAME 선수
FROM(SELECT A.*,ROWNUM AS RNUM 
        FROM
            (SELECT P.BIRTH_DATE,P.PLAYER_NAME
             FROM PLAYER P
             WHERE P.BIRTH_DATE IS NOT NULL
             ORDER BY P.BIRTH_DATE desc
             ) A )
WHERE RNUM BETWEEN 6 AND 10
ORDER BY RNUM ASC;




SELECT COUNT(*) 선수인원 --468명    
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC
;

